spyndra:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: motor_f1
    pid: {p: 1.0, i: 0.01, d: 0.01}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: motor_t1
    pid: {p: 1.0, i: 0.01, d: 0.01}
